services:

  webserver:
    build:
      context: ./bin/webserver-${PHP_VERSION}
      args:
        PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME}
        PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
        PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE}
        PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE}
    container_name: ${COMPOSE_PROJECT_NAME}-webserver
    restart: always
    depends_on:
      - database
    ports:
      - ${APACHE_HOST_HTTP_PORT}:80
      - ${APACHE_HOST_HTTPS_PORT}:443
    volumes:
      - ${APACHE_DATA_DIR}:/var/www/html
      - ${APACHE_LOG_DIR}:/var/log/apache2
    tty: true

  database:
    image: mariadb:lts
    container_name: ${COMPOSE_PROJECT_NAME}-database
    restart: always
    ports:
      - ${DB_HOST_PORT}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - ${DB_DATA_DIR}:/var/lib/mysql
      - ${DB_LOG_DIR}:/var/log/mysql
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - ${PMA_HOST_PORT}:80
    environment:
      PMA_HOST: database
      PMA_PORT: ${DB_HOST_PORT}
      MAX_EXECUTION_TIME: ${PMA_MAX_EXECUTION_TIME}
      MEMORY_LIMIT: ${PMA_MEMORY_LIMIT}
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT}
